name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4.3.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Load Google Services File
      env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -di > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
